In [1]:
import numpy as np 
import pandas as pd  
import sklearn
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score

In [2]:
df = pd.read_excel('table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls', header=4 )
df.head(5)

City  Population  Violent\ncrime  \
0             Adams Village      1861.0             0.0   
1  Addison Town and Village      2577.0             3.0   
2             Akron Village      2846.0             3.0   
3                    Albany     97956.0           791.0   
4            Albion Village      6388.0            23.0   

   Murder and\nnonnegligent\nmanslaughter  Rape\n(revised\ndefinition)1  \
0                                     0.0                           NaN   
1                                     0.0                           NaN   
2                                     0.0                           NaN   
3                                     8.0                           NaN   
4                                     0.0                           NaN   

   Rape\n(legacy\ndefinition)2  Robbery  Aggravated\nassault  Property\ncrime  \
0                          0.0      0.0                  0.0             12.0   
1                          0.0      0.0                  3.0             24.0   
2                          0.0      0.0                  3.0             16.0   
3                         30.0    227.0                526.0           4090.0   
4                          3.0      4.0                 16.0            223.0   

   Burglary  Larceny-\ntheft  Motor\nvehicle\ntheft  Arson3  
0       2.0             10.0                    0.0     0.0  
1       3.0             20.0                    1.0     0.0  
2       1.0             15.0                    0.0     0.0  
3     705.0           3243.0                  142.0     NaN  
4      53.0            165.0                    5.0     NaN

In [3]:
list(df.columns)

['City',
 'Population',
 'Violent\ncrime',
 'Murder and\nnonnegligent\nmanslaughter',
 'Rape\n(revised\ndefinition)1',
 'Rape\n(legacy\ndefinition)2',
 'Robbery',
 'Aggravated\nassault',
 'Property\ncrime',
 'Burglary',
 'Larceny-\ntheft',
 'Motor\nvehicle\ntheft',
 'Arson3']

In [4]:
df['Rape\n(revised\ndefinition)1'].unique()

array([nan])

In [5]:
df = df.drop(columns='Rape\n(revised\ndefinition)1')
df.head()

City  Population  Violent\ncrime  \
0             Adams Village      1861.0             0.0   
1  Addison Town and Village      2577.0             3.0   
2             Akron Village      2846.0             3.0   
3                    Albany     97956.0           791.0   
4            Albion Village      6388.0            23.0   

   Murder and\nnonnegligent\nmanslaughter  Rape\n(legacy\ndefinition)2  \
0                                     0.0                          0.0   
1                                     0.0                          0.0   
2                                     0.0                          0.0   
3                                     8.0                         30.0   
4                                     0.0                          3.0   

   Robbery  Aggravated\nassault  Property\ncrime  Burglary  Larceny-\ntheft  \
0      0.0                  0.0             12.0       2.0             10.0   
1      0.0                  3.0             24.0       3.0             20.0   
2      0.0                  3.0             16.0       1.0             15.0   
3    227.0                526.0           4090.0     705.0           3243.0   
4      4.0                 16.0            223.0      53.0            165.0   

   Motor\nvehicle\ntheft  Arson3  
0                    0.0     0.0  
1                    1.0     0.0  
2                    0.0     0.0  
3                  142.0     NaN  
4                    5.0     NaN

In [6]:
df = df.rename(columns={'City':'city','Population':'population','Violent\ncrime':'violent_crime',
 'Murder and\nnonnegligent\nmanslaughter':'murder_manslaughter',
 'Rape\n(legacy\ndefinition)2':'rape',
 'Robbery':'robbery',
 'Aggravated\nassault':'aggravated_assult',
 'Property\ncrime':'property_crime',
 'Burglary':'burglary',
 'Larceny-\ntheft':'larceny_theft',
 'Motor\nvehicle\ntheft':'car_theft',
 'Arson3':'arson'}) 
df.head()

city  population  violent_crime  murder_manslaughter  \
0             Adams Village      1861.0            0.0                  0.0   
1  Addison Town and Village      2577.0            3.0                  0.0   
2             Akron Village      2846.0            3.0                  0.0   
3                    Albany     97956.0          791.0                  8.0   
4            Albion Village      6388.0           23.0                  0.0   

   rape  robbery  aggravated_assult  property_crime  burglary  larceny_theft  \
0   0.0      0.0                0.0            12.0       2.0           10.0   
1   0.0      0.0                3.0            24.0       3.0           20.0   
2   0.0      0.0                3.0            16.0       1.0           15.0   
3  30.0    227.0              526.0          4090.0     705.0         3243.0   
4   3.0      4.0               16.0           223.0      53.0          165.0   

   car_theft  arson  
0        0.0    0.0  
1        1.0    0.0  
2        0.0    0.0  
3      142.0    NaN  
4        5.0    NaN

In [7]:
df['arson'].fillna(0,inplace=True)
df.head()

city  population  violent_crime  murder_manslaughter  \
0             Adams Village      1861.0            0.0                  0.0   
1  Addison Town and Village      2577.0            3.0                  0.0   
2             Akron Village      2846.0            3.0                  0.0   
3                    Albany     97956.0          791.0                  8.0   
4            Albion Village      6388.0           23.0                  0.0   

   rape  robbery  aggravated_assult  property_crime  burglary  larceny_theft  \
0   0.0      0.0                0.0            12.0       2.0           10.0   
1   0.0      0.0                3.0            24.0       3.0           20.0   
2   0.0      0.0                3.0            16.0       1.0           15.0   
3  30.0    227.0              526.0          4090.0     705.0         3243.0   
4   3.0      4.0               16.0           223.0      53.0          165.0   

   car_theft  arson  
0        0.0    0.0  
1        1.0    0.0  
2        0.0    0.0  
3      142.0    0.0  
4        5.0    0.0

In [8]:
df.isnull().sum()

city                   0
population             3
violent_crime          3
murder_manslaughter    3
rape                   3
robbery                3
aggravated_assult      3
property_crime         3
burglary               3
larceny_theft          3
car_theft              3
arson                  0
dtype: int64

In [9]:
df.dropna(how='any', inplace=True )

In [10]:
df1=df[['city','property_crime','population','murder_manslaughter','robbery']]

In [11]:
df1['populationsq'] = df1['population']**2
df1.head()

/Users/christianfreeman/anaconda3/envs/thinkful2/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


city  property_crime  population  murder_manslaughter  \
0             Adams Village            12.0      1861.0                  0.0   
1  Addison Town and Village            24.0      2577.0                  0.0   
2             Akron Village            16.0      2846.0                  0.0   
3                    Albany          4090.0     97956.0                  8.0   
4            Albion Village           223.0      6388.0                  0.0   

   robbery  populationsq  
0      0.0  3.463321e+06  
1      0.0  6.640929e+06  
2      0.0  8.099716e+06  
3    227.0  9.595378e+09  
4      4.0  4.080654e+07

In [12]:
df1['murder'] = (df['murder_manslaughter'] > 0).astype(int)
df1.head()

/Users/christianfreeman/anaconda3/envs/thinkful2/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


city  property_crime  population  murder_manslaughter  \
0             Adams Village            12.0      1861.0                  0.0   
1  Addison Town and Village            24.0      2577.0                  0.0   
2             Akron Village            16.0      2846.0                  0.0   
3                    Albany          4090.0     97956.0                  8.0   
4            Albion Village           223.0      6388.0                  0.0   

   robbery  populationsq  murder  
0      0.0  3.463321e+06       0  
1      0.0  6.640929e+06       0  
2      0.0  8.099716e+06       0  
3    227.0  9.595378e+09       1  
4      4.0  4.080654e+07       0

In [13]:
data1 = df1

In [14]:
data1['robbery'] = (df1['robbery'] > 0).astype(int)
data1.head()

/Users/christianfreeman/anaconda3/envs/thinkful2/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


city  property_crime  population  murder_manslaughter  \
0             Adams Village            12.0      1861.0                  0.0   
1  Addison Town and Village            24.0      2577.0                  0.0   
2             Akron Village            16.0      2846.0                  0.0   
3                    Albany          4090.0     97956.0                  8.0   
4            Albion Village           223.0      6388.0                  0.0   

   robbery  populationsq  murder  
0        0  3.463321e+06       0  
1        0  6.640929e+06       0  
2        0  8.099716e+06       0  
3        1  9.595378e+09       1  
4        1  4.080654e+07       0

In [15]:
data = data1[['city','population','populationsq','robbery','murder','property_crime']]
data.tail()

city  population  populationsq  robbery  murder  \
343      Woodbury Town     10685.0  1.141692e+08        1       0   
344  Woodridge Village       829.0  6.872410e+05        0       0   
345     Woodstock Town      5931.0  3.517676e+07        0       0   
346            Yonkers    199134.0  3.965435e+10        1       1   
347      Yorktown Town     36643.0  1.342709e+09        1       0   

     property_crime  
343           541.0  
344            17.0  
345            58.0  
346          2368.0  
347           334.0

In [16]:
from sklearn import linear_model
import statsmodels.formula.api as smf
data['property_crime'] = (data['property_crime'] >0).astype(int)
data.head()

/Users/christianfreeman/anaconda3/envs/thinkful2/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


city  population  populationsq  robbery  murder  \
0             Adams Village      1861.0  3.463321e+06        0       0   
1  Addison Town and Village      2577.0  6.640929e+06        0       0   
2             Akron Village      2846.0  8.099716e+06        0       0   
3                    Albany     97956.0  9.595378e+09        1       1   
4            Albion Village      6388.0  4.080654e+07        1       0   

   property_crime  
0               1  
1               1  
2               1  
3               1  
4               1

In [17]:
regr = linear_model.LinearRegression()
y = df['property_crime'].values.reshape(-1, 1)
x = df[['robbery','population','burglary', 'car_theft']]
regr.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(x, y))


Coefficients: 
 [[ 0.52690689  0.01226282  3.71301785 -4.40432191]]

Intercept: 
 [-23.03128994]

R-squared:
0.9996184306558658


In [19]:
0.52690689*0+0.01226282*1861+3.71301785*2+-4.40432191*0+-23.03128994169049

7.215853778309512

In [20]:
df.describe()

population  violent_crime  murder_manslaughter         rape  \
count  3.480000e+02     348.000000           348.000000   348.000000   
mean   4.003763e+04     201.594828             1.566092     5.864943   
std    4.500374e+05    2815.268504            18.303673    60.425452   
min    5.260000e+02       0.000000             0.000000     0.000000   
25%    3.003000e+03       2.000000             0.000000     0.000000   
50%    7.233500e+03       6.000000             0.000000     0.000000   
75%    1.842750e+04      22.000000             0.000000     2.000000   
max    8.396126e+06   52384.000000           335.000000  1112.000000   

            robbery  aggravated_assult  property_crime      burglary  \
count    348.000000         348.000000      348.000000    348.000000   
mean      72.902299         121.261494      792.606322    119.683908   
std     1031.032873        1706.131730     7659.724746    924.948789   
min        0.000000           0.000000        0.000000      0.000000   
25%        0.000000           1.000000       40.500000      6.000000   
50%        1.000000           4.000000      112.500000     17.500000   
75%        5.000000          14.000000      341.000000     51.250000   
max    19170.000000       31767.000000   141971.000000  16606.000000   

       larceny_theft    car_theft       arson  
count     348.000000   348.000000  348.000000  
mean      637.017241    35.905172    1.005747  
std      6346.054451   403.423826    7.884612  
min         0.000000     0.000000    0.000000  
25%        31.000000     0.000000    0.000000  
50%        94.000000     2.000000    0.000000  
75%       287.250000     7.000000    0.000000  
max    117931.000000  7434.000000  132.000000

In [21]:
cross_val_score(regr, x,y, cv=20 )

array([0.95979245, 0.99964507, 0.88926068, 0.88352507, 0.66542344,
       0.92572439, 0.77891296, 0.95275874, 0.89113255, 0.88823194,
       0.79795569, 0.86561797, 0.95186313, 0.70037771, 0.83881775,
       0.99034521, 0.97778225, 0.99053928, 0.90873901, 0.70094542])

In [24]:
x1 = df[['robbery','population','burglary']]
cross_val_score(regr, x1,y, cv=20 )

array([0.95074402, 0.99755127, 0.90400431, 0.92215686, 0.67456418,
       0.92875349, 0.81648815, 0.94181156, 0.89254642, 0.85964198,
       0.70046779, 0.87961297, 0.92539014, 0.66588795, 0.95423943,
       0.98807081, 0.98335627, 0.98644905, 0.93421914, 0.64205872])

In [26]:
property_crime = y
linear_formula = 'property_crime ~ robbery+population+burglary'
lm = smf.ols(formula=linear_formula, data=x1).fit()


I chose to use K folds with 20 folds. I used 20 because 20 with floor division evenly goes into the total number of events that occured. 

In [28]:
lm.params

Intercept    -23.707388
robbery       -0.848130
population     0.012806
burglary       3.053095
dtype: float64

In [29]:
lm.pvalues

Intercept      2.637854e-02
robbery        3.910943e-04
population     1.401938e-91
burglary      9.398219e-161
dtype: float64

In [30]:
lm.rsquared

0.9995866510973678

In [ ]:
I used k folds method because the variables were linear and there was a substatial number of rows.